#!/usr/bin/env node
/**
 * build-dict.mjs — regenerate assets/data/cedict.tsv.gz
 *
 * Turns the upstream CC-CEDICT release (and, optionally, jieba's frequency
 * table) into the single compact file the reader at /chinese/ downloads.
 *
 *   node script/build-dict.mjs                    # download both sources
 *   node script/build-dict.mjs --cedict path.u8   # use a local CC-CEDICT
 *   node script/build-dict.mjs --no-freq          # skip jieba frequencies
 *
 * Output format — one entry per line, tab separated, UTF-8, gzipped:
 *
 *   simplified <TAB> traditional <TAB> pinyin <TAB> freq <TAB> sense/sense/…
 *
 * `traditional` is left empty when it is identical to the simplified form
 * (true for roughly half the dictionary, and worth about 8% of the file).
 * `pinyin` keeps CC-CEDICT's numbered tones; the browser converts them to
 * tone marks at render time. `freq` is a jieba corpus count used only to
 * score the segmenter's candidate splits — 0 means "not in jieba".
 *
 * Licensing: CC-CEDICT is CC BY-SA, jieba's dictionary is MIT. The licence
 * header of the CC-CEDICT release is copied verbatim into the output as
 * leading `#` comment lines, which the parser skips.
 */

import { createWriteStream } from "node:fs";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { gzipSync } from "node:zlib";
import path from "node:path";

const CEDICT_URL = "https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz";
const JIEBA_URL = "https://raw.githubusercontent.com/fxsjy/jieba/master/jieba/dict.txt";
const OUT = "assets/data/cedict.tsv.gz";

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const opt = (name) => {
  const i = args.indexOf(name);
  return i === -1 ? null : args[i + 1];
};

async function loadText(localPath, url, { gunzip = false } = {}) {
  if (localPath) {
    const buf = await readFile(localPath);
    return buf.toString("utf8");
  }
  process.stderr.write(`fetching ${url}\n`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (!gunzip) return buf.toString("utf8");
  const { gunzipSync } = await import("node:zlib");
  return gunzipSync(buf).toString("utf8");
}

/** CC-CEDICT line: 漢字 汉字 [han4 zi4] /Chinese character/CL:個|个[ge4]/ */
const LINE = /^(\S+)\s+(\S+)\s+\[([^\]]*)\]\s+\/(.*)\/\s*$/;

function parseCedict(text) {
  const header = [];
  const entries = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#")) {
      // Keep the licence/version block, drop the machine-readable noise.
      if (header.length < 40) header.push(line.replace(/^#!?\s*/, "").trim());
      continue;
    }
    const m = LINE.exec(line);
    if (!m) continue;
    const [, trad, simp, pinyin, defs] = m;
    entries.push({
      simp,
      trad: trad === simp ? "" : trad,
      pinyin: pinyin.trim(),
      defs: defs.split("/").map((d) => d.trim()).filter(Boolean),
    });
  }
  return { header, entries };
}

/** jieba dict line: 中国 3055 ns */
function parseJieba(text) {
  const freq = new Map();
  for (const raw of text.split("\n")) {
    const parts = raw.split(" ");
    if (parts.length < 2) continue;
    const word = parts[0];
    const n = Number.parseInt(parts[1], 10);
    if (!word || !Number.isFinite(n)) continue;
    if (n > (freq.get(word) ?? 0)) freq.set(word, n);
  }
  return freq;
}

const HELP = `Usage: node script/build-dict.mjs [options]

  --cedict <file>  read CC-CEDICT from a local file instead of downloading
                   (the plain cedict_ts.u8, not the .gz)
  --freq <file>    read jieba's dict.txt from a local file
  --no-freq        build without frequencies; the segmenter then falls back
                   to preferring the fewest, longest words
  --help           show this

Writes ${OUT}.
`;

const main = async () => {
  if (flag("--help") || flag("-h")) {
    process.stdout.write(HELP);
    return;
  }
  const cedictText = await loadText(opt("--cedict"), CEDICT_URL, { gunzip: true });
  const { header, entries } = parseCedict(cedictText);
  if (entries.length < 1000) throw new Error("CC-CEDICT parse produced too few entries");

  let freq = new Map();
  if (!flag("--no-freq")) {
    freq = parseJieba(await loadText(opt("--freq"), JIEBA_URL));
  }

  const lines = [];
  lines.push("# Generated by script/build-dict.mjs — do not edit by hand.");
  lines.push("# Dictionary data from CC-CEDICT, licensed CC BY-SA. https://cc-cedict.org/");
  lines.push("# Word frequencies from jieba (MIT). https://github.com/fxsjy/jieba");
  for (const h of header) if (h) lines.push(`# ${h}`);

  let withFreq = 0;
  let maxLen = 0;
  for (const e of entries) {
    // A handful of entries carry tabs or stray control characters.
    const defs = e.defs.map((d) => d.replace(/[\t\n\r]+/g, " ")).join("/");
    const f = freq.get(e.simp) ?? 0;
    if (f) withFreq += 1;
    maxLen = Math.max(maxLen, [...e.simp].length);
    lines.push(`${e.simp}\t${e.trad}\t${e.pinyin}\t${f}\t${defs}`);
  }

  const body = lines.join("\n") + "\n";
  const gz = gzipSync(Buffer.from(body, "utf8"), { level: 9 });
  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, gz);

  const mb = (n) => (n / 1024 / 1024).toFixed(2);
  process.stderr.write(
    `${OUT}\n` +
      `  entries        ${entries.length}\n` +
      `  with frequency ${withFreq}\n` +
      `  longest headword ${maxLen} characters\n` +
      `  raw ${mb(Buffer.byteLength(body))} MB → gzip ${mb(gz.length)} MB\n`
  );
};

main().catch((err) => {
  process.stderr.write(`${err.stack || err}\n`);
  process.exit(1);
});
